# Generated by Django 5.2 on 2025-05-04 08:17

import base.db.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_category_type_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date this record was updated.', verbose_name='Update Date')),
                ('name', models.CharField(help_text='This is the expense name.', max_length=50, validators=[base.db.validators.BlankValidator(code='invalid_expense_name', message='Expense name must not be blank')], verbose_name='Expense Name')),
                ('description', models.CharField(help_text='This is the expense description.', max_length=250, verbose_name='Expense Description')),
                ('date', models.DateField(help_text='This is expense date', verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='This is the expense amount', max_digits=12, validators=[base.db.validators.BlankValidator(code='invalid_expense_amount', message='Expense Amount must not be blank')], verbose_name='Expense Amount')),
                ('source', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=1, help_text='This is the source of the expense', verbose_name='Expense Source')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, validators=[base.db.validators.BlankValidator()]), default=None, null=True, size=None, verbose_name='Expense Tags')),
                ('category', models.ForeignKey(help_text='The type of category this expense is.', on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='category.category')),
            ],
            options={
                'db_table': 'expense',
                'indexes': [models.Index(fields=['created_at'], name='expense_created_0a6070_idx'), models.Index(fields=['updated_at'], name='expense_updated_cb386e_idx')],
            },
        ),
    ]
