# Generated by Django 5.2 on 2025-05-04 08:18

import base.db.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_category_type_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date this record was updated.', verbose_name='Update Date')),
                ('name', models.CharField(help_text='This is the income name.', max_length=50, validators=[base.db.validators.BlankValidator(code='invalid_income_name', message='Income name must not be blank')], verbose_name='Income Name')),
                ('description', models.CharField(help_text='This is the income description.', max_length=250, verbose_name='Income Description')),
                ('date', models.DateField(help_text='This is income date', verbose_name='Income Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='This is the Income amount', max_digits=12, validators=[base.db.validators.BlankValidator(code='invalid_income_amount', message='Income Amount must not be blank')], verbose_name='Income Amount')),
                ('source', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=1, help_text='This is the source of the income', verbose_name='Income Source')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, validators=[base.db.validators.BlankValidator()]), default=None, null=True, size=None, verbose_name='Income Tags')),
                ('category', models.ForeignKey(help_text='The type of category this income is.', on_delete=django.db.models.deletion.PROTECT, related_name='income', to='category.category')),
            ],
            options={
                'db_table': 'income',
                'indexes': [models.Index(fields=['created_at'], name='income_created_140c95_idx'), models.Index(fields=['updated_at'], name='income_updated_71969b_idx')],
            },
        ),
    ]
