# Generated by Django 5.2 on 2025-05-04 08:17

import base.db.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(1, 'Expense'), (2, 'Income')], default=1, help_text='This is the category type', verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'A category with that name already exists!'}, help_text='This is the expense category name.', max_length=50, unique=True, validators=[base.db.validators.BlankValidator(code='invalid_category_name', message='Category name must not be blank')], verbose_name='Category Name'),
        ),
    ]
